on: push
jobs:
  run_server_tests:
    name: Run server test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24.1.0"
      - name: Install
        working-directory: app
        run: |
          pip3 install uv
          uv sync
      - name: lint
        working-directory: app
        run: |
          uv run ruff check
          uv run ruff format --check
      - name: Run tests
        working-directory: app
        run: |
          uv run pytest tests
      - name: generate docker
        run: |
          docker build -t ghcr.io/danielhstahl/householdhelper-app -f docker/app.Dockerfile .
  run_rust_tests:
    name: Run rust test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        working-directory: draid
        run: |
          cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
          cat lcov.info
        env:
          SQLX_OFFLINE: true # needed to keep it from trying to connect to a database

      - name: generate docker
        run: |
          docker build -t ghcr.io/danielhstahl/householdhelper-draid -f docker/draid.Dockerfile .

  run_ui_tests:
    name: Run UI tests
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
      VITEST_SEGFAULT_RETRY: "5"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24.1.0"
      - name: install deps
        working-directory: ui
        run: |
          npm ci
          npx playwright install-deps
          npx playwright install
      - name: run tests
        working-directory: ui
        run: npm run test -- --coverage .
      - name: compile
        working-directory: ui
        run: npm run build

      - name: generate docker
        run: |
          docker build -t ghcr.io/danielhstahl/householdhelper-ui -f docker/ui.Dockerfile .
