on: push
jobs:
  run_server_tests:
    name: Run server test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24.1.0"
      - name: Install
        run: |
          pip3 install uv
          uv sync
      - name: lint
        run: |
          uv run ruff check
          uv run ruff format --check
      - name: Run tests
        run: |
          uv run pytest tests

  run_ui_tests:
    name: Run UI tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./household-droid
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
      VITEST_SEGFAULT_RETRY: "5"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24.1.0"
      - name: install deps
        run: |
          npm ci
          npx playwright install-deps
          npx playwright install
      - name: run tests
        run: npm run test -- --coverage .
      - name: compile
        run: npm run build
